[phases.setup]
packages = ["dotnet-sdk-6.0"]

[phases.install]
commands = ["dotnet restore"]

[phases.build]
commands = ["dotnet publish -c Release -o out"]

[phases.start]
commands = ["dotnet out/GolfScoreBot.dll"]
