[phases.setup]
packages = ["dotnet-sdk-6.0"]

[phases.install]
commands = ["cd src && dotnet restore --disable-parallel"]

[phases.build]
commands = ["cd src && dotnet publish -c Release -o ../out"]

[phases.start]
commands = ["dotnet out/GolfScoreBot.dll"]
