[build]
# .NET SDK version
dotnet-version = "6.0"

[install]
# Dependencies to restore
packages = []

[build.commands]
# Restore and publish the project
restore = "dotnet restore"
publish = "dotnet publish -c Release -o out"

[start]
# Start the bot from the published output
command = "./out/GolfScoreBot"
